environment:
  matrix:
    # TODO: Need to fix extension to enable Python 2.7
    # - PYTHON: "C:\\Python27"
    #   TOX_ENV: py27
    # - PYTHON: "C:\\Python27-x64"
    #   TOX_ENV: py27
    - PYTHON: "C:\\Python35"
      TOX_ENV: py35
    - PYTHON: "C:\\Python35-x64"
      TOX_ENV: py35
    - PYTHON: "C:\\Python36"
      TOX_ENV: py36
    - PYTHON: "C:\\Python36-x64"
      TOX_ENV: py36
    - PYTHON: "C:\\Python37"
      TOX_ENV: py37
    - PYTHON: "C:\\Python37-x64"
      TOX_ENV: py37
install:
  - "%PYTHON%\\python.exe -m pip install -U tox wheel"
build: off
test_script:
  - "%PYTHON%\\python.exe --version"
  #- "build.cmd %PYTHON%\\Scripts\\tox -e %TOX_ENV%"
after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"
artifacts:
  - path: dist\*
